In [2]:
import pandas as pd

training_data=pd.read_csv("../data/cs-training.csv")

In [3]:


print(training_data.info())
print(training_data.shape)
print(training_data.isna().sum())
print(training_data.isna().mean())

print(training_data["SeriousDlqin2yrs"].sum())
print(training_data["SeriousDlqin2yrs"].mean())

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 12 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Unnamed: 0                            150000 non-null  int64
 1   SeriousDlqin2yrs                      150000 non-null  int64
 2   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 3   age                                   150000 non-null  int64
 4   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  int64
 5   DebtRatio                             150000 non-null  float64
 6   MonthlyIncome                         120269 non-null  float64
 7   NumberOfOpenCreditLinesAndLoans       150000 non-null  int64
 8   NumberOfTimes90DaysLate               150000 non-null  int64
 9   NumberRealEstateLoansOrLines          150000 non-null  int64
 10  NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  int64
 11  NumberOfDependents                    146076 non-null  float64
dtypes: float64(4), int64(8)
memory usage: 13.7 MB
None
(150000, 12)
Unnamed: 0                                  0
SeriousDlqin2yrs                            0
RevolvingUtilizationOfUnsecuredLines        0
age                                         0
NumberOfTime30-59DaysPastDueNotWorse        0
DebtRatio                                   0
MonthlyIncome                           29731
NumberOfOpenCreditLinesAndLoans             0
NumberOfTimes90DaysLate                     0
NumberRealEstateLoansOrLines                0
NumberOfTime60-89DaysPastDueNotWorse        0
NumberOfDependents                       3924
dtype: int64
Unnamed: 0                              0.000000
SeriousDlqin2yrs                        0.000000
RevolvingUtilizationOfUnsecuredLines    0.000000
age                                     0.000000
NumberOfTime30-59DaysPastDueNotWorse    0.000000
DebtRatio                               0.000000
MonthlyIncome                           0.198207
NumberOfOpenCreditLinesAndLoans         0.000000
NumberOfTimes90DaysLate                 0.000000
NumberRealEstateLoansOrLines            0.000000
NumberOfTime60-89DaysPastDueNotWorse    0.000000
NumberOfDependents                      0.026160
dtype: float64
10026
0.06684

In [4]:
training_data.describe().T.reset_index()

,index,count,mean,std,min,25%,50%,75%,max
0,Unnamed: 0,150000.0,75000.500000,43301.414527,1.0,37500.750000,75000.500000,112500.250000,150000.0
1,SeriousDlqin2yrs,150000.0,0.066840,0.249746,0.0,0.000000,0.000000,0.000000,1.0
2,RevolvingUtilizationOfUnsecuredLines,150000.0,6.048438,249.755371,0.0,0.029867,0.154181,0.559046,50708.0
3,age,150000.0,52.295207,14.771866,0.0,41.000000,52.000000,63.000000,109.0
4,NumberOfTime30-59DaysPastDueNotWorse,150000.0,0.421033,4.192781,0.0,0.000000,0.000000,0.000000,98.0
5,DebtRatio,150000.0,353.005076,2037.818523,0.0,0.175074,0.366508,0.868254,329664.0
6,MonthlyIncome,120269.0,6670.221237,14384.674215,0.0,3400.000000,5400.000000,8249.000000,3008750.0
7,NumberOfOpenCreditLinesAndLoans,150000.0,8.452760,5.145951,0.0,5.000000,8.000000,11.000000,58.0
8,NumberOfTimes90DaysLate,150000.0,0.265973,4.169304,0.0,0.000000,0.000000,0.000000,98.0
9,NumberRealEstateLoansOrLines,150000.0,1.018240,1.129771,0.0,0.000000,1.000000,2.000000,54.0
10,NumberOfTime60-89DaysPastDueNotWorse,150000.0,0.240387,4.155179,0.0,0.000000,0.000000,0.000000,98.0
11,NumberOfDependents,146076.0,0.757222,1.115086,0.0,0.000000,0.000000,1.000000,20.0

In [5]:
training_data.groupby(training_data['MonthlyIncome'].isna())['RevolvingUtilizationOfUnsecuredLines'].describe()

,count,mean,std,min,25%,50%,75%,max
MonthlyIncome,,,,,,,,
False,120269.0,5.899873,257.040685,0.0,0.035084,0.177282,0.579428,50708.0
True,29731.0,6.649421,217.814854,0.0,0.016027,0.081697,0.440549,22198.0

In [6]:
training_data.groupby(training_data['MonthlyIncome'].isna())['DebtRatio'].describe()

,count,mean,std,min,25%,50%,75%,max
MonthlyIncome,,,,,,,,
False,120269.0,26.598777,424.446457,0.0,0.143388,0.296023,0.482559,61106.5
True,29731.0,1673.396556,4248.372895,0.0,123.000000,1159.000000,2382.000000,329664.0

In [11]:
training_data['income_missing']=training_data['MonthlyIncome'].isna()

training_data.groupby('income_missing')['SeriousDlqin2yrs'].agg(
    count='count',
    default='sum',
    default_rate='mean'
)

                 count  default  default_rate
income_missing
False           120269     8357      0.069486
True             29731     1669      0.056137

In [12]:
training_data['dependents_missing']=training_data['NumberOfDependents'].isna()

training_data.groupby('dependents_missing')['SeriousDlqin2yrs'].agg(
    count='count',
    default='sum',
    default_rate='mean'
)

                     count  default  default_rate
dependents_missing
False               146076     9847      0.067410
True                  3924      179      0.045617